### ISSUE TITLE
RCON messages doesn't response to Go program.

### ISSUE THREAD

**Issue by Sauce233** [mcstatus-io/mcutil#8]
When I use the RCON function of this Go library v3.3.0 version, the command was successfully sent to my Minecraft server, 
![image](https://github.com/mcstatus-io/mcutil/assets/134782569/600eb07c-dca2-42bc-9189-6987ec9975db)
but my Go program didn't output any response of this operation.
![image](https://github.com/mcstatus-io/mcutil/assets/134782569/bc0417f5-0397-4d54-8128-7fd9901b7e0d)
And the program didn't stop.
This is my code:
![image](https://github.com/mcstatus-io/mcutil/assets/134782569/7db908ae-6d2c-4ac6-9e10-3d08507c9a04)
My Minecraft version is Paper 1.20.4

**Comment by PassTheMayo** [comment]
I was able to reproduce this issue on my end and I have pushed `v3.4.0` which should fix this issue for you.
